// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateApi.Data;

#nullable disable

namespace RealEstateApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RealEstateApi.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrokerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("RealEstateApi.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("RealEstateApi.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<int>("BrokerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 3200,
                            Bathrooms = 3,
                            Bedrooms = 4,
                            BrokerId = 1,
                            Description = "Breathtaking 32nd-floor penthouse with panoramic city views, floor-to-ceiling glass, designer kitchen, and rooftop terrace.",
                            ImageUrl = "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
                            Location = "Manhattan, New York",
                            Price = 4500000m,
                            Title = "Skyline Penthouse",
                            Type = "Penthouse"
                        },
                        new
                        {
                            Id = 2,
                            Area = 5800,
                            Bathrooms = 5,
                            Bedrooms = 6,
                            BrokerId = 1,
                            Description = "Stunning beachfront estate with private pool, home theater, gourmet kitchen, and direct beach access on the Pacific Ocean.",
                            ImageUrl = "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
                            Location = "Malibu, California",
                            Price = 8900000m,
                            Title = "Oceanfront Villa",
                            Type = "Villa"
                        },
                        new
                        {
                            Id = 3,
                            Area = 1800,
                            Bathrooms = 2,
                            Bedrooms = 2,
                            BrokerId = 1,
                            Description = "Stylish converted industrial loft with exposed brick, polished concrete floors, and stunning river views in the heart of Chicago.",
                            ImageUrl = "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
                            Location = "Chicago, Illinois",
                            Price = 1200000m,
                            Title = "Downtown Loft",
                            Type = "Loft"
                        },
                        new
                        {
                            Id = 4,
                            Area = 4500,
                            Bathrooms = 4,
                            Bedrooms = 5,
                            BrokerId = 1,
                            Description = "Luxury ski-in/ski-out chalet with stone fireplace, heated floors, wine cellar, and sweeping Rocky Mountain vistas.",
                            ImageUrl = "https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=800&q=80",
                            Location = "Aspen, Colorado",
                            Price = 6200000m,
                            Title = "Mountain Retreat",
                            Type = "Chalet"
                        },
                        new
                        {
                            Id = 5,
                            Area = 2200,
                            Bathrooms = 2,
                            Bedrooms = 3,
                            BrokerId = 1,
                            Description = "Modern townhouse in a vibrant neighborhood with smart home features, rooftop deck, and a lush private garden.",
                            ImageUrl = "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80",
                            Location = "Austin, Texas",
                            Price = 980000m,
                            Title = "Garden Townhouse",
                            Type = "Townhouse"
                        });
                });

            modelBuilder.Entity("RealEstateApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "broker@demo.com",
                            Name = "Alice (Broker)",
                            PasswordHash = "$2a$11$KzJhIv/gAuHiUBXEfYZAMuY0bGJM9ZZM9D3Ol3J7yEFQ.jCvFWkde",
                            Role = "broker"
                        },
                        new
                        {
                            Id = 2,
                            Email = "customer@demo.com",
                            Name = "Bob (Customer)",
                            PasswordHash = "$2a$11$KzJhIv/gAuHiUBXEfYZAMuY0bGJM9ZZM9D3Ol3J7yEFQ.jCvFWkde",
                            Role = "customer"
                        });
                });

            modelBuilder.Entity("RealEstateApi.Models.Booking", b =>
                {
                    b.HasOne("RealEstateApi.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateApi.Models.Property", "Property")
                        .WithMany("Bookings")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RealEstateApi.Models.Favorite", b =>
                {
                    b.HasOne("RealEstateApi.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealEstateApi.Models.Property", "Property")
                        .WithMany("Favorites")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RealEstateApi.Models.Property", b =>
                {
                    b.HasOne("RealEstateApi.Models.User", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("RealEstateApi.Models.Property", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
